vich_uploader:
    db_driver: orm

    mappings:

        adverts_images:
            uri_prefix: '%adverts_images%'
            upload_destination: '%kernel.project_dir%/public%adverts_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
